**General Services Administration**

Federal Acquisition Service

Technology Transformation Services

1800 F St NW | Washington, DC | 20405

Office of Products and Programs  
Search.gov Development Support

**R**equest for Quote

**From:** Kirsten Green, Contracting Officer, General Services
Administration, Technology Transformation Services, Office of
Acquisitions

**Posting Date:** June 8, 2018

**Question and Answer Close Date:** Noon EST on June 15, 2018  
**Quote Due By:** Noon EST on June 22, 2018

**Set Aside:** 100% 8(a)

**Contract Vehicle:** GSA Schedule 70, SIN 132-51 Information Technology
Professional

# Instructions

General Services Administration (GSA), Technology Transformation
Services (TTS), Office of Acquisitions (OA) hereby issues this Request
for Quote (RFQ) and associated attachments, under Federal Acquisition
Regulation (FAR) 8.405-2 for Office of Products and Programs (OPP)
Search.gov Development Support.

## RFQ Attachments - All Attachments can be found on e-Buy and GitHub

Attachment 1 - Quality Assurance Surveillance Plan (QASP)

Attachment 2 - RFQ Pricing Form - Search.gov Development Support

Link 1 - [<span class="underline">GSA TTS Search.gov Development Support
RFQ Response
Form</span>](https://goo.gl/forms/E0paZGTllbPnxIlT2)

Link 2 - GitHub Repo:
[<span class="underline">18F</span>](https://github.com/18F)/<span class="underline">tts-buy-searchgov-development</span>

## Quote Instructions

The Quoter shall submit a quote in accordance with the instructions and
terms and conditions of this RFQ and the terms and conditions of its GSA
Schedule contract.

Unless expressly authorized by the RFQ, any Quoter planning to take
exception to a term or condition of the RFQ should consult with the
Contracting Officer (CO) in writing before submitting a quote.

**RFQ Question and Answer (Q\&A) Period:**

\- Quoters shall submit all questions concerning this RFQ by creating an
Issue using the Issue Template in the associated
[<span class="underline">GitHub
repository</span>](https://github.com/18F/tts-buy-searchgov-development.git.).

\- Questions submitted in in other manner will not be accepted.

\- Quoters shall submit Questions as soon as possible, but no later than
Noon EST on June 15, 2018.

\- The Government will provide answers via Github Open Issues no later
than Noon EST on June 18, 2018. The Q\&A will also be posted as an
amendment on GSA E-Buy.

**Technical Submittal:**

The Quoter shall submit a technical response, in accordance with the
RFQ, via the [<span class="underline">GSA TTS Search.gov Development
Support RFQ Response
Form</span>](https://goo.gl/forms/E0paZGTllbPnxIlT2).

**Price Submittal:**

The Quoter shall propose a discount at or below their GSA IT Schedule 70
Contract discount amount for the Base Year, Option Years and Optional
Tasks. The Quoter shall provide a detailed price quote that clearly
identifies the proposed GSA labor mix/categories and level of
effort/associated rates, via the [<span class="underline">RFQ Pricing
Form - Search.gov Development
Support</span>](https://docs.google.com/spreadsheets/d/1bmsshuqnFdhFXky6QEMJW_6ldgAedUAi_MFJKGwOtSc/edit?usp=sharing)
found at the [<span class="underline">GitHub
page</span>](https://github.com/18F/tts-buy-searchgov-development.git).
Quoters shall download the Pricing Form, fill in the information
required, and upload it to Section 5 on the [<span class="underline">GSA
TTS Search.gov Development Support RFQ Response
Form</span>](https://goo.gl/forms/E0paZGTllbPnxIlT2).

Quotes are due as soon as possible, but no later than Noon EST on June
22, 2018.

# Evaluation Criteria and Basis of Award

This procurement is being conducted in accordance with FAR Subpart 8.4,
Federal Supply Schedules. FAR Part 15, Contracting by Negotiation,
procurement procedures are not being utilized, except procedures within
FAR Part 15.4, Contract Pricing may be utilized, as allowed, for price
analysis. All submissions in response to this RFQ are considered
quotations and not proposals or offers, even if labeled as such. The
offerors agree to and are bound by all instructions, procedures and
rules of this RFQ. The Government is not obligated to determine a
competitive range, conduct discussions, solicit final revised
quotations, and use other techniques associated with FAR part 15.

The final award for this requirement will be based on best-value
principles, utilizing the trade-off process. Accordingly, award will be
made to the responsible and technically acceptable quote who provides
the greatest overall value to the Government, price and other factors
considered.

The Government is more concerned with obtaining superior technical and
management capabilities than with making an award at the lowest overall
price to the Government. Quoters are advised that the technical
evaluation factors combined are significantly more important than price.

# Evaluation Process

The Government intends to utilize a multi-phased approach for this
procurement as described below. To be considered for award, each Quote
must successfully pass through each phase.

Phase 1: Technical Evaluation - The Government will evaluate the Quoters
Technical Submittal, as provided in the GSA TTS search.gov Development
Support RFQ Response Form. Quotes found to be technically acceptable
will move on to oral interviews.

Phase 2: The Oral Interview will be focused on the offeror’s technical
approach, staffing plan, and similar experience, as well as their
overall understanding of the requirements to perform the factors
outlined in the solicitation. The oral interview is an opportunity for
the Government to ask the vendor questions -- the Government does not
want vendor presentations during this interview.

Phase 3: Pricing Submittal - Quoter’s Price, as provided in the RFQ
Pricing Form - Search.gov Development Support, will be reviewed
separately from the technical evaluation and will only include Quotes
who pass the oral interview.

**Evaluation Factors**

The Government will evaluate the Quoters performance or capability
acceptability based on the following non-price technical factors, listed
in descending order of importance. For this solicitation, technical
factors are more important than price.

**Factor 1: Technical Approach**

The Quoter shall succinctly describe its technical approach for the
requirement as set forth in the PWS. This document should clearly
demonstrate how the Quote intends to satisfy the objectives and
requirements of the RFQ. This document shall not exceed 10 pages in
length.

**Factor 2: Staffing Plan **

The Quote shall succinctly describe a Staffing Plan for the
requirements. The staffing plan should be no more than 6 pages,
excluding resumes. This document should include the following:

  - > Description of your staffing methodology based on your
    > understanding of the requirements stated in the RFQ.

  - > A breakdown of the number of personnel by skill levels/labor
    > categories, including the title, number of personnel, and level of
    > effort/hours needed to satisfy the objectives and requirements of
    > the RFQ. All proposed skill levels/labor categories shall be
    > consistent with the Quoters GSA IT Schedule 70 contract. The
    > breakdown should be in-line with the information submitted on the
    > RFQ Pricing Form.

<!-- end list -->

  - > A list of Key Personnel by name, title, contact information,
    > proposed duties and roles, along with a resume for each proposed
    > Key Personnel in accordance with Personnel section of the PWS.
    > Resumes should include a description of the experience and
    > capability for all Key Personnel proposed for the Quoters project
    > team. Resumes should also address the individual’s technical
    > background, education, work experience, and accomplishments
    > related to the activities described in the attached PWS. Any key
    > personnel not currently employed by the Quoters or teaming
    > partners shall be accompanied by letters of intent signed by
    > proposed Key Personnel in accordance with the PWS.

**Factor 3: Similar Experience **

Describe the experience and capability of your organization in
conducting similar work. This document shall not exceed a total of 10
pages in length.

The work must have been performed by either:

1.  > The Quoter itself, or

2.  > A teaming partner or subcontractor that is proposed in response to
    > this RFQ, or

3.  > Any Key Personnel who are being proposed in response to this RFQ.

In the project summary, be sure to identify how the Quoter’s team on the
prior project was involved in the development.

Here, “similar work" is meant to convey similarity in subject matter,
dollar value, duration, and complexity, such as the following key areas:

  - > Writing and using Application Programming Interfaces (APIs)

  - > Ruby on Rails

  - > Maintaining applications with high uptime and low latency

  - > Elasticsearch, Logstash, and Kibana

  - > The plugins offered in the Elastic X-Pack

  - > Hosting and deploying Amazon Web Services (AWS)

  - > Configuration management solutions such as Chef

  - > Containerization tools such as Docker

  - > Federal IT system security compliance, including the Assessment &
    > Authorization process

  - > How the company plans for to deliver new features or functionality
    > in their products. Please provide examples of features introduced
    > to products after they have been in production.

  - > How the company identifies items to be added to a roadmap, the
    > approach to prioritization of the items and how the roadmap is
    > delivered.

While the Government may elect to consider data from other sources, the
burden of providing detailed, current, accurate and complete similar
experience information rests with the Quoter.

At a minimum, the quote shall include:

  - > A narrative describing similar experience with a search service or
    > other high volume application. Please provide examples of up to
    > three (3) projects, within the past 3 years, of similar subject
    > matter, dollar value, duration, and complexity as that outlined by
    > the RFQ. The narrative shall include the point of contacts for the
    > projects.

  - > The narrative shall include links to the public Git repository
    > that includes the source code that was developed and accepted for
    > the project. Actual access to a publicly available Git repository,
    > an anonymized fork of a private repository, or an anonymized fork
    > of a repository with Personally Identifiable Information/sensitive
    > information is strongly encouraged over screenshots of private
    > repositories. The summary should also include live links of the
    > final product or current staging environment. If live links are
    > not available, screenshots may be provided, along with a brief
    > explanation as to why the project is no longer live. The projects
    > should be recent and similar to the size and technical scope of
    > this requirement.

  - > The company’s experience working with and maintaining open source
    > software.

## Oral Interview Process

The Government is much more interested in the informational content of
the Quoters answers than the particular style or technique used in
delivering the answers. The Government may take notes during the
presentation at its discretion, and may use such notes in the
evaluation. No copies will be provided to any Quoters.

**Schedule and Agenda for oral interviews**

<table>
<thead>
<tr class="header">
<th><strong>Agenda Item</strong></th>
<th><strong>Time Allocated</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Introductions</td>
<td>Approximately 5 Minutes</td>
</tr>
<tr class="even">
<td>Quoter Orals - Q&amp;A on Technical Factors</td>
<td>60 Minutes Maximum--but may go shorter</td>
</tr>
<tr class="odd">
<td>Break for Quoter &amp; Government Questions</td>
<td>5 Minutes Maximum</td>
</tr>
<tr class="even">
<td>Government Follow-Up Q&amp;A<br />
(if needed)</td>
<td>15 Minutes Maximum--but may go shorter</td>
</tr>
</tbody>
</table>

##   
Oral Interview Rules

The oral interview, consisting of an initial question and answer session
on technical factors and a follow-up question and answer session (if
necessary), does not and will not constitute as discussions or
negotiations. The Government is not obligated to determine a competitive
range, conduct discussions, and solicit or allow revised quotes. Quote
revisions will not be requested or accepted during oral interviews.

The oral interview sessions will be conducted by video. The Government
will coordinate and set up the meeting space accordingly (providing dial
in or links using tools such as appear.in, Zoom, or Google Hangouts).
Quoters shall not bring or present slides, graphs, charts or any other
written presentation materials nor will the Government accept or receive
Quoters handouts.

The Government will schedule the date and time of the oral interviews
with each Quoter, in random order, after the RFQ closing date and
receipt of quote submissions. The Government reserves the right to
reschedule any Quoters oral interview date at the discretion of the CO.

The Quoter may include as many participants as it feels is necessary and
is the full responsibility of the Quoter. Quoters are advised to have
technical personnel present since the Government will ask technical
questions during the oral interviews. All proposed Key Personnel
currently employed by the Quoter or its teaming partners shall attend
the session - the Government is most interested in hearing from staff
that will have a direct role in performing on the task. The letter(s) of
intent and resume(s) will suffice for Key Personnel currently not
employed by the Quoter or its teaming partners.  
After the presentations, Quoters shall provide an email with names of
participants to the CO.

Quoters oral interview will consist of the offeror answering the
Government’s questions related to the technical factors identified in
the RFQ and the Quoters technical understanding and approach of the
requirements identified in the PWS. The Government’s questions may
differ among the Quoters based on what needs elaboration.

If necessary, the Government will ask follow-up questions regarding the
Quoters answers to the questions on technical factors. During this time,
the Government may ask questions on any information presented by the
Quoter that the Government feels is unclear or needs elaboration. The
Government’s questions may differ among the Quoters based on what needs
elaboration. If the Government has no follow-up questions with a
particular Quoter, then this part of the session will not take place.
The answers given in this session are part of the Quoters oral
interview.

# Factor 4: Price

Each Quoters price quote, including the Base Year, Option Years and
Optional Tasks, will be evaluated separately from the technical
quotation and oral interview. The Government will evaluate the Quoters
pricing schedule after the Oral Interview in order to ensure that the
offered price is fair, reasonable, and realistic. Pricing shall reflect
reasonableness, consistency with industry standards, and be in
compliance with rates and terms and conditions in the GSA IT Schedule 70
SIN 132-51 contract. Note that as submissions become more technically
equal in their merit, the evaluated price becomes more important.
Therefore, Quoters are encouraged to provide their best discounted rates
up front.

Performance Work Statement

# Background

The General Services Administration (GSA), Federal Acquisition Service
(FAS), Technology Transformation Services (TTS), Office of Products and
Programs (OPP) is the sponsoring organization for
[<span class="underline">Search.gov</span>](https://search.gov/).

For over 15 years, Search.gov has helped change the public’s search
experience and saved Government agencies and partners valuable resources
and money by providing hosted site search services, compiling not only
webpage results, but also content posted to social media, news and blogs
via RSS feeds, job listings and Federal Register documents, for about
1,900 Government websites. Search.gov’s primary goals are as follows:

  - > Ongoing support and continuous development of the Search.gov
    > application (Ruby on Rails / Elasticsearch stack) and
    > infrastructure, currently Amazon Web Services (AWS) East-West),
    > including increased implementation of open source in the
    > Search.gov stack.

  - > Sourcing from multiple platforms, develop central indexes of
    > agency content for use in agency search results. Platforms
    > include, but are not limited to, websites and feeds, social media,
    > and unique Government sources such as the Federal Register,
    > MedlinePlus, USAJobs, etc.

  - > Participation in GSA continuous monitoring, vulnerability scanning
    > and remediation processes.

  - > Support federal team in providing technical support to customers.

# Scope of Work

To continue to successfully achieve Search.gov’s mission, Search.gov
requires the support of a qualified Contractor, who uses
[<span class="underline">the twelve
principles</span>](http://agilemanifesto.org/principles.html)
established by the [<span class="underline">Agile
Manifesto.</span>](http://agilemanifesto.org/)
[<span class="underline">The contractor will be
required</span>](http://agilemanifesto.org/) to provide a team of search
developers and system administration professionals and maintain the
current environment and development and deployment of new features.

The Contractor shall use existing user stories, as prioritized by the
GSA TTS Product Owner in a Product Backlog, to guide development and
maintenance. Additionally, the Contractor shall create new user stories
in consultation with the GSA TTS Product Owner. Completion of all user
stories shall be determined in accordance with the standards established
in the project’s “Definition of Done” as discussed in the QASP, allowing
for continuous testing and review. It is expected that everything that
is actually delivered will be contractually “acceptable” as well as
practically usable.

## Tasks

The Contractor shall complete the following Tasks:

**Task 1.** Provide search results for agencies, by maintaining and
developing the following core components, meeting or exceeding industry
standards for network latency and uptime:

1.  > A hosted search results page.

2.  > Indexes of agency content, currently in Elasticsearch. Indexes are
    > created via API, RSS, and by a crawler/parser. Content includes
    > websites, social media, and unique Government sources such as
    > USAJobs and the *Federal Register*.

3.  > The Search.gov Admin Center, currently a Ruby on Rails application
    > that allows customer agency staff to configure the search
    > experience they want to provide to their users.

4.  > Near-real time search analytics for agency customers, available
    > through the Admin Center. When possible, this data will be opened
    > and published in cooperation with other GSA programs.

5.  > The Search.gov Super Admin backend, for use by Search.gov team
    > members to manage privileged functions for search site and system
    > settings.

**Task 2.** Introduce new features and functions to respond to evolving
public expectations for search, and evolving system requirements.

**Task 3.** Support the Search.gov website, the primary help manual for
the service. Support includes writing and managing content and
infrastructural support. The site is currently published using GitHub
Pages using Jekyll.

**Task 4.** Support the interface between Search.gov and relevant
commercial search engines, including data management, communication, and
administrative tasks.

**Task 5.** Manage the system infrastructure:

1.  > Maintain low latency and high uptime for the application.

2.  > Perform work related to planned outages, such as production
    > pushes, outside of the core business hours of 8:30 a.m. and 6:00
    > p.m. Eastern Time (ET). Minimize outage times.

3.  > Respond to unplanned outages within 10 minutes between 6 a.m. and
    > 10 p.m. ET. Any outages after 10 p.m. ET shall be responded to by
    > 6:30 a.m. ET. Maintain performance monitoring tools that promptly
    > and automatically notify the Contractor team of outages.
    > Participate in GSA’s security scanning, monitoring, and
    > authorization activities as needed, and remediate any issues in
    > accordance with GSA Security requirements.

4.  > Contractor shall maintain logically isolated environments, in an
    > infrastructure provided by GSA, currently AWS East-West to support
    > development, integration, acceptance testing, troubleshooting, and
    > all pre-production, as well as production, activities.

**Task 6.** Create new search system components as open source code.
Contribute code to other open source projects as appropriate.

**Task 7.** Provide content support, including:

1.  > Maintaining the list of Government domains, segmented by federal,
    > state, local, tribal and territorial.

2.  > Maintaining type-ahead filters, synonyms, misspellings, and other
    > Search.gov language handling tools.

3.  > Analyzing search query data and conducting research (such as
    > identifying authoritative Government datasets, market research,
    > industry benchmarking, or an environmental scan of the federal web
    > space) in support of new feature development.

4.  > Creating wireframes for the search results page and Admin Center.

5.  > Testing user stories.

6.  > Writing help documentation.

**Task 8.** Provide customer service support to potential and current
customers, using [<span class="underline">plain
language</span>](https://plainlanguage.gov/about/definitions/), as
approved by the Search.gov Product Lead, including:

1.  > Assisting the Search.gov Product Lead in phone and email outreach
    > to federal agencies to market the service.

2.  > Assisting the Search.gov Product Lead in outreach and support at
    > conferences, webinars, and other venues and via social media.

3.  > Notifying customers of new Search.gov features or other pertinent
    > information via email on a regular basis.

4.  > Responding to potential and current customers’ support questions
    > (currently submitted via phone and email), providing an initial
    > response within one (1) business day and resolving the questions
    > in a timely manner.

### **OPTIONAL TASKS 1 - 3**

The following tasks may or may not be awarded via modification pending
availability of funds. The Contractor shall not perform work on any of
these tasks until they have been added via modification and are given a
notice to proceed from the CO. If the Contractor performs any of the
work prior to a modification, they do so at their own risk. The
Contractor shall provide prices for all tasks, including optional tasks.
The Contractor will be asked to hold the proposed prices.

**Optional Task 1.** Upon execution of a modification and notice to
proceed by the CO: Search Engine Optimization (SEO) support and
research, to be provided by Librarians and/or other Information
Specialists:

  - > SEO analysis and consultations for customer agency websites

  - > Support and labor hours to implement SEO best practices on
    > customer agency websites

**Optional Task 2.** Upon execution of a modification and notice to
proceed by the CO: Development and/or Support of a centrally managed CDN
and/or hosted 301 Redirects service: the volume of 301 Redirects
required to adequately support the access flow for Government web
information over time is significant, and often beyond a given agency’s
technical capacity.

**Optional Task 3.** Upon execution of a modification and notice to
proceed by the CO: Development and/or Support of a hosted XML sitemaps
service: XML sitemaps are a key element in search engine optimization,
allowing sites to proactively inform search engines about new and
updated content, and also the relative importance of different content
on the site. Agencies with static websites or certain content management
systems often lack the ability to create and maintain an XML sitemap.

# Transition Period/Plan

The Contractor recognizes that the services under this contract are
vital to the Government and must be continued without interruption and
that, upon contract expiration, a successor, either the Government or
another contractor, may continue them. Up to eight (8) weeks before the
end of the period of performance, the Contractor agrees to:

1.  > Document and provide support for transition of services to another
    > environment

2.  > Provide sufficient experienced personnel during the phase-in,
    > phase-out period to ensure that the services called for by this
    > contract are maintained at the required level of proficiency.

3.  > Exercise its best efforts and cooperation to effect an orderly and
    > efficient transition to a successor.

# Contractor Employee/Personnel Requirements

## Contractor Employee Identification

When on-site, all Contractor personnel shall comply with all Government
rules and requirements pertaining to access to facilities and
information systems. All Contractor personnel shall identify themselves
as Contractors when their status is not readily apparent and display all
identification and visitor badges in plain view at all appropriate times
while on-site.

##   
Employee Conduct

The Government may, at its sole discretion, direct the Contractor to
remove any Contractor personnel from government facilities for any
unprofessional behavior, general misconduct, or breaches of security, as
deemed appropriate by the COR/CO. Removal does not relieve the
Contractor of the responsibility to continue providing the services
required under this Task Order. Furthermore, the Contractor shall
promptly replace the removed employee with another employee within the
same labor category within 5 business days.

# Contractor Furnished Property/Equipment

All on-site and off-site Contractor personnel are required to work with
their own laptop resources with Microsoft Office Suite (Word, Excel and
PowerPoint), a wireless card and account, and an email account
(corporate or free). Only federal Government laptops may directly access
the GSA networks. However, Contractors may use corporate or personal
laptops within the building to access the Internet via guest wireless
provided by the Government. It is a requirement that these resources be
available to personnel for the duration of their performance on this
contract.

The Contractor shall ensure all team members have access to relevant
systems and accounts within 14 calendar days after award.

# Kickoff Meeting

The Government's team, CO/COR and the GSA TTS Product Owner, will hold a
kickoff meeting with the contractor within 5 calendar days of the
acquisition award, unless otherwise agreed upon by all parties in
writing (email will be sufficient). This kickoff will include the
contractor’s team and other relevant government staff to review and
clarify the project’s objectives, expectations from the government, and
address any questions the contractor may have.

# Deliverables 

All deliverables will be inspected for content, completeness, accuracy,
and conformance with the Task Order requirements by the Government.
Inspection may include validation of information or software through the
use of automated tools and/or testing of the deliverables, as specified
in the Task Order. The scope and nature of this testing must be
negotiated prior to Task Order award and shall be sufficiently
comprehensive to ensure the completeness, quality and adequacy of all
deliverables.

The Government requires a period not to exceed thirty (30) days after
receipt of final deliverable items for inspection and acceptance or
rejection.

## Place of Delivery

The Contractor shall deliver all work to the GSA TTS Product Lead for
Search.gov. Deliverables may be delivered to GSA’s Google Drive, GitHub,
via email, or occasionally in hard copy to Search.gov - QXD, GSA, FAS,
TTS, 1800 F Street NW, Washington, DC 20405.

## Basis of Acceptance

Search.gov develops, tests, approves or rejects, and releases approved
new code to production in an incremental manner. The GSA TTS Product
Owner and the Contractor will agree on a protocol for testing and
production pushes. Written deliverables, such as research reports or
data will be reviewed and approved by the COR and GSA TTS Product Owner.
All of the Government’s comments to deliverables must either be
incorporated in the succeeding version or the Contractor shall
demonstrate to the Government’s satisfaction why such comments should
not be incorporated.

<table>
<thead>
<tr class="header">
<th><blockquote>
<p><strong>Reference</strong></p>
</blockquote></th>
<th><blockquote>
<p><strong>Deliverable</strong></p>
</blockquote></th>
<th><blockquote>
<p><strong>Description</strong></p>
</blockquote></th>
<th><blockquote>
<p><strong>Initial Due Date</strong></p>
</blockquote></th>
<th><blockquote>
<p><strong>Subsequent</strong></p>
</blockquote></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>NA</td>
<td>Discovery Sprint - Summary of findings</td>
<td>Written or verbal notification of learning from Discovery Sprint - deep dive into code and other as-is aspects of the service</td>
<td>Within 14 calendar days after award</td>
<td><blockquote>
<p>NA</p>
</blockquote></td>
</tr>
<tr class="even">
<td><blockquote>
<p>Task 2</p>
</blockquote></td>
<td><blockquote>
<p>Strategic Roadmap</p>
</blockquote></td>
<td><blockquote>
<p>To support product design, program management, and communications about development plans</p>
</blockquote></td>
<td><blockquote>
<p>Within 3 months of award</p>
</blockquote></td>
<td><blockquote>
<p>Quarterly</p>
</blockquote></td>
</tr>
<tr class="odd">
<td><blockquote>
<p>Task 2</p>
</blockquote></td>
<td><blockquote>
<p>Project plans</p>
</blockquote></td>
<td><blockquote>
<p>For major system changes, provide a detailed plan for the successful delivery of the project</p>
</blockquote></td>
<td><blockquote>
<p>As needed</p>
</blockquote></td>
<td><blockquote>
<p>As needed</p>
</blockquote></td>
</tr>
<tr class="even">
<td><blockquote>
<p>Tasks 2, 5, 6, &amp; 7b</p>
</blockquote></td>
<td><blockquote>
<p>Source code</p>
</blockquote></td>
<td><blockquote>
<p>Per GSA policy, code must be checked in daily</p>
</blockquote></td>
<td><blockquote>
<p>Daily</p>
</blockquote></td>
<td><blockquote>
<p>Ongoing</p>
</blockquote></td>
</tr>
<tr class="odd">
<td><blockquote>
<p>Task 7a</p>
</blockquote></td>
<td><blockquote>
<p>List of Government domains</p>
</blockquote></td>
<td><blockquote>
<p>The list of Government domains supports the whole-Government scope of the USA.gov search</p>
</blockquote></td>
<td><blockquote>
<p>Quarterly</p>
</blockquote></td>
<td><blockquote>
<p>Quarterly, according to Microsoft Bing schedule</p>
</blockquote></td>
</tr>
<tr class="even">
<td>NA</td>
<td>Monthly performance metrics</td>
<td><blockquote>
<p>Specific metrics to be determined by the Search.gov GSA TTS Product Owner</p>
</blockquote></td>
<td><blockquote>
<p>Monthly</p>
</blockquote></td>
<td>By the 10th of every month, with the invoice</td>
</tr>
<tr class="odd">
<td>NA</td>
<td>Monthly status report</td>
<td><blockquote>
<p>A report of work accomplished, and work in progress.</p>
</blockquote></td>
<td><blockquote>
<p>Monthly</p>
</blockquote></td>
<td>By the 10th of every month, with the invoice</td>
</tr>
<tr class="even">
<td>NA</td>
<td>Transition plan</td>
<td></td>
<td><blockquote>
<p>No later than 8 weeks prior to end of final period of performance</p>
</blockquote></td>
<td></td>
</tr>
</tbody>
</table>

# Quality Assurance

The Government will use the attached draft Quality Assurance
Surveillance Plan (QASP) to monitor the Contractor’s performance. The
QASP will provide oversight help to ensure that service levels reach and
maintain the required levels for performance of this task. Further, the
QASP provides the Government with a proactive way to avoid unacceptable
or deficient performance, and provides verifiable input for the required
Past Performance Information Assessments. The QASP is a living document
and may be updated by the Government as necessary. Any updates to the
QASP will be provided to the Contractor at the time of the update.

# Contractor Performance

Performance will be documented in Contractor Performance Assessment
Report (CPARs) at the end of each performance period (for both base and
option years). Interim reports may also be used. Should deficiencies in
performance occur, the Contractor may be notified by the CO/COR in oral
or written format. The Government may require the Contractor to
re-perform any services that do not conform to order requirements.

# Personnel

## Required Knowledge

The Contractor’s staff shall possess the combination of knowledge,
specialized skills and abilities to assist the Government in achieving
Search.gov’s goals and objectives and in meeting its federal regulatory
and policy requirements.

The Contractor shall provide a team of specialized professionals in
support of Search.gov. This team shall support all research,
development, operations and maintenance, and customer service required
to meet Search.gov’s goals and objectives.

Areas of expertise required:

  - > Elasticsearch, Versions 1.7.x and 5.6.x

  - > Ruby on Rails, Versions 4.2 and 5.x

  - > Chef, Version 12

  - > Amazon Web Services

Additionally, a team assigned to perform this work is expected to have
experience with:

  - > Agile development practices

  - > Test-driven development

  - > Information Architecture, including system design

  - > DevOps practices, including monitoring

  - > Building and testing public-facing sites and tools

  - > Highly-responsive systems, meaning response times of 750
    > millisecond or less

The Contractor shall provide people who are comfortable working with a
geographically distributed team and who can leverage the existing tools
used by the program, or new tools as become available and are approved
for use by GSA. The Government will choose from the tools above (or
Contractor proposed equivalent or superior) based on its needs at the
time of award.

## 

## Key Personnel

The Government considers Key Personnel to include all Contractor team
members (e.g. firm employees, independent contractors, subcontractor
employees, etc.) necessary to demonstrate the contractor’s technical
capability to deliver the requirements of this Task Order. Designation
as Key Personnel is not tied to any specific labor category, function,
or level, and is at the sole discretion of the contractor.

At a minimum, the contractor shall identify one member of the Key
Personnel that:

  - > Has a full understanding of the technical approach discussed
    > during the Oral Interview and delivered by the contractor after
    > award;

  - > Will be a direct liaison to the CO, COR and GSA TTS Product Owner.
    > In this capacity, this individual shall be responsible for the
    > supervision and management of the contractor’s personnel,
    > technical assistance, and interface.

## Key Personnel Changes

If any individual proposed as Key Personnel becomes unavailable during
the course of the solicitation, evaluation process or period of
performance, the contractor shall notify the CO immediately. Any Key
Personnel proposed who are not currently employed by the contractor
shall be identified as such and an additional letter of intent signed by
the proposed Key Personnel shall be provided that indicates that
person's intent to be employed by the contractor if awarded this Task
Order.

The contractor agrees that through the duration of the period of
performance of the Task Order, no Key Personnel substitutions shall be
made unless necessitated by an individual’s sudden illness, death, or
termination of employment for cause. In any of such event, the
contractor shall promptly notify the CO, COR, and the GSA TTS Product
Owner and provide the information required by paragraphs below on the
proposed replacement for Government approval.  
  
All requests for substitutions/additions of Key Personnel must include a
detailed explanation of the circumstances necessitating the proposed
substitution or addition. As determined by the CO, all proposed
substitutes/additions must have qualifications that meet or exceed the
qualifications of the person to be replaced or supplemented.  
  
The CO, with input from the COR and the GSA TTS Product Owner, will
evaluate the request(s) for substitutions/additions of Key Personnel and
the CO will notify the contractor, in writing, of approval or
disapproval. Disapproval of the proposed individual(s) shall not provide
grounds for non-performance by the contractor or form the basis of any
claim for monies, delivery schedule extension, or any other equitable
adjustment.

# 

# Travel

Travel to attend in-person meetings held in the Washington,
DC-Metropolitan Area may be required. All travel will be in accordance
with the Federal Travel Regulations.

The Contractor shall obtain written approval from the GSA TTS Product
Owner at least 1 week prior to traveling. The Government is not
obligated to pay for travel taken by the Contractor without proper
authorization. The Contractor shall submit an email to the GSA TTS
Product Owner and include the following information:

  - > Travelers Name, and purpose of travel

  - > Task Order Number

  - > State the destination(s), origin, departure date, return date, and
    > number of days

  - > Include travel estimates to include, airfare, lodging, rental car,
    > per diem, mileage, and any reimbursable items (metro, parking,
    > etc.)

Travel will be billed separately and at a reimbursable, Not-To-Exceed
(NTE) amount. If additional funds are required, the Contractor must seek
modification for increase prior to approval. If the NTE is exceeded
without modification and/or approval, the Government reserves the right
to reject invoices for travel in excess of the established NTE amount.

# Terms & Conditions

## Contract Type & Contract Line Item Numbers

The Government intends to award a Time and Materials (T\&M) Task Order
under GSA Information Technology (IT) Schedule 70, Special Item Number
(SIN) 132-51 Information Technology Professional Services. The Contract
Line Item Numbers (CLIN’s) are as follows:

Base Year

  - > 0001: Search.gov Development Support Services (T\&M)

  - > 0002: Optional Tasks 1 - 3 (T\&M)

  - > 0003: Travel (NTE)

Option Year 1

  - > 1001: Search.gov Development Support Services (T\&M)

  - > 1002: Optional Tasks 1 - 3 (T\&M)

  - > 1003: Travel (NTE)

Option Year 2

  - > 2001: Search.gov Development Support Services (T\&M)

  - > 2002: Optional Tasks 1 - 3 (T\&M)

  - > 2003: Travel (NTE)

Option Year 3

  - > 3001: Search.gov Development Support Services (T\&M)

  - > 3002: Optional Tasks 1 - 3 (T\&M)

  - > 3003: Travel (NTE)

Option Year 4

  - > 4001: Search.gov Development Support Services (T\&M)

  - > 4002: Optional Tasks 1 - 3 (T\&M)

  - > 4003: Travel (NTE)

The Contractor shall not make expenditures, nor incur obligations, in
the performance of this contract, which exceeds the current available
funding amount specified herein, except at the Contractor’s own risk.

The Contractor shall notify the Contracting Officer (CO), in writing, 60
days prior to incurring 75% of the obligated funding, or whenever there
is reason to believe that costs may be either greater or substantially
less than previously estimated, or are not adequate to complete the
balance of work remaining in the contract. If remaining funds are
inadequate, include:

1.  > A fully supported price proposal disclosing the amount of funds
    > remaining

2.  > The amount of additional funding required to continue timely
    > performance

3.  > When the funds will be required

**INCREMENTAL FUNDING**

The obligated funding under this Task Order at time of award for the
base period will be stated on the award documentation. Additionally,
funding may be added by the execution of modifications to the Task
Order, up to the ceiling amount for the applicable performance period.
The Contractor shall note that residual funding at the end of a
performance period may be deobligated through a bilateral modification;
inclusion of this funding in the following performance period is subject
to budget approval based on appropriations and fiscal constraints.

## Period of Performance

The Period of Performance (POP) will be a Base Year plus 4 Option Years.

## Place of Performance/Hours

The primary place of performance will be at the contractor's facility.
Work may also be performed at GSA, TTS, 1800 F Street NW, Washington,
D.C. 20405.

The Contractor will not be required to work on the following federal
holidays:  
  
New Year’s Day Birthday of Martin Luther King, Jr.  
Washington’s Birthday Memorial Day  
Independence Day Labor Day  
Columbus Day Veterans Day  
Thanksgiving Day Christmas Day

## Government Points of Contact

GSA Contracting Officer (CO): Kirsten Green,
[<span class="underline">kirsten.green@gsa.gov</span>](mailto:kirsten.green@gsa.gov)

GSA Contracting Officer’s Representative (COR): Will be provided at time
of award

GSA TTS Product Owner: Will be provided at time of award

## Government Furnished Property/Equipment

The Government will provide desk seating, via the GSA hoteling system,
for the Contractor while working on-site. No equipment will be provided.

## Government Furnished Information

The Government will furnish the following information:

  - > Existing user stories

  - > Access to AWS accounts

  - > Access to GSA GitHub organization and repos

  - > Access to Search.gov monitoring tools, logs and reports

  - > Access to GSA email and drives.

  - > Access to commercial search engine resources, such as webmaster
    > tools accounts and configuration panels

## All Material Property of U.S. Government

All materials developed under this Task Order are property of the U.S.
Government. Under no circumstances shall the Contractor place a
copyright on any of the materials that the Contractor develops, provides
and receives payment for under Task Order.

## Data Rights and Ownership of Deliverables

GSA TTS intends that any data or deliverable created as a result of the
work performed under the call order be committed to the public domain.

Further, GSA TTS intends to commit the following items, to the public
domain, at a minimum:

  - > All data, documents, graphics and code created under this call
    > order including but not limited to, plans, reports, schedules,
    > schemas, metadata, architecture designs, and the like;

  - > Any and all new open source software created by the contractor and
    > forks or branches of current open source software where the
    > contractor has made a modification; and,

  - > Any and all new tooling, scripting configuration management,
    > infrastructure as code, or any other final changes or edits to
    > successfully deploy or operate the software.

The contractor shall use open source technologies wherever possible, in
support of the [<span class="underline">18F Source Code
Policy</span>](https://18f.gsa.gov/open-source-policy/). All licenses
must be expressly listed in the deliverable. Regardless of license(s)
used (e.g., MIT, GPL, Creative Commons 0) the license(s) shall be
clearly listed in the documentation.

If the contractor needs to use work that does not have an open source
license, the contractor is required to request permission from GSA TTS,
in writing, before utilizing that work in any way in connection with the
order. If approved, all licenses shall be clearly set forth in a
conspicuous place when work is delivered to GSA TTS.

If an open source license provides implementation guidance, the
contractor shall ensure compliance with that guidance. If implementation
guidance is not available, the contractor shall attach or include the
license within the work itself. Examples of this include code comments
at the beginning of a file or contained in a license file within a
software repository.

## Privacy Act

Performance of this Task Order may require that personnel have access to
Privacy Information. Contractor personnel shall adhere to the Privacy
Act, Title 5 of the U.S. Code, Section 552a and any other applicable
applicable rules and regulations.

## Sensitive Information Storage

Sensitive But Unclassified (SBU) information, data, and/or equipment
shall only be disclosed to authorized personnel on a Need-To-Know basis.
The Contractor shall ensure that appropriate administrative, technical,
and physical safeguards are established to ensure the security and
confidentiality of this information, data, and/or equipment is properly
protected. When no longer required, this information, data, and/or
equipment shall be returned to Government control; destroyed; or held
until otherwise directed. Destruction of items shall be accomplished by
tearing into small parts; burning; shredding or any other method that
precludes the reconstruction of the material. All sensitive information
contained on Contractor computers shall be either degaussed or shall use
the Department of Defense method of a three time overwrite of the
sensitive data.

## Protection of Information

The Contractor shall be responsible for properly protecting all
information used, gathered, disclosed, or developed as a result of work
under this contract. The Contractor shall also protect all Government
data by treating information as sensitive. All information gathered or
created under this contract shall be considered as Sensitive but
Unclassified (SBU) information. The use of this data is subject to the
Privacy Act and shall be utilized in full accordance with all rules of
conduct as applicable to Privacy Act Information.

## Transparency Policy

The Contractor is advised that GSA TTS will publish on a publicly
available website documents associated with this requirement, including
any Requests for Quotation (including amendments), Question and Answer
exchanges with Contractors (source-identifying information removed), and
other relevant information that is not confidential/proprietary in
nature or source selection sensitive information that would otherwise
implicate procurement integrity concerns.

Upon award, GSA TTS will publish the total price of the selected
proposal and certain non-source-identifying data (e.g., the number of
bids, the mean price, median, and standard deviation of price). During
the performance of this call order, GSA TTS will similarly publish
source code, data related to project management (e.g., user stories,
milestones, and performance metrics), and top-line spending data.

## Confidentiality and Nondisclosure

It is recognized by the parties that, in the course of the Contractor's
activities, its personnel may require access to or be given custody of
certain information (whether in its original or derived form) submitted
to the Government on a confidential basis (such as other Government
Contractors' business practices, designs, mission or operation concepts,
sketches, management policies, cost and operating expenses, technical
data and similar information) during the performance of the contract.
The Contractor agrees that its employees with access shall use and
examine this information exclusively in performance of the work required
under this contract and for no other purpose whatsoever. The Contractor
agrees to provide training to all personnel who shall have access to or
custody of the information as to the nature of the confidential
relationship under which the Government received such information, and
to stress that the information must not be disclosed to any other party
or to Contractor personnel who do not have a need to know the contents
thereof for the performance of this contract. All personnel shall also
be informed that they must not engage in any other action, venture or
employment wherein this information could be used for the profit or
interest of any party.

## Organizational Conflicts of Interest

All contractor key personnel, employees, agents, subcontractors and
subcontractor personnel who will have access to documents or data during
the performance of their duties under the contract shall execute a
Non-Disclosure Agreement and return it to the CO within 5 calendar days
of award and before being given access to such information or documents.

The Contractor’s attention is directed to Federal Acquisition Regulation
(FAR) Subpart 9.5, Organizational and Consultant Conflicts of Interest.

## Section 508 Compliance

The Contractor shall support the Government in its compliance with
Section 508 throughout the development and implementation of the work to
be performed.

Section 508 of the Rehabilitation Act of 1973, as amended (29 U.S.C.
794d) requires that when Federal agencies develop, procure, maintain, or
use electronic information technology, Federal employees with
disabilities have access to and use of information and data that is
comparable to the access and use by Federal employees who do not have
disabilities, unless an undue burden would be imposed on the agency.
Section 508 also requires that individuals with disabilities, who are
members of the public seeking information or services from a Federal
agency, have access to and use of information and data that is
comparable to that provided to the public who are not individuals with
disabilities, unless an undue burden would be imposed on the agency.

# INVOICES

The Contractor shall submit a proper invoice on a monthly basis.

## Content of Invoice

In addition to the items below, the Contractor shall submit proper
invoices as specified in FAR 52.212-4(g):

  - > Contract/Order Number - Provided at time of award

  - > Period of Performance covered by the invoice

  - > Contract Line Item Number (CLIN)

The Contractor shall submit a final invoice at the end of the period of
performance within 60 calendar days after contract completion. No
further charges are to be billed following the final invoice submission.
With the submission of a final invoice, a completed and signed Release
of Claims (GSA Form 1142) shall be provided to the CO.

## Invoice Submission

The Contractor shall submit invoices to *GSA Vendor Customer Self
Service (VCSS)* and the COR. All invoicing questions can be directed to
customer support at 866-450-6588 or the VCSS customer service site
[<span class="underline">https://vcss.ocfo.gsa.gov/</span>](https://vcss.ocfo.gsa.gov/).
GSA TTS is unable to address any questions related to the invoicing
system.

# Federal Laws and Regulations Relevant to Search.gov

The Contractor shall comply with all following applicable Federal Laws
and Regulations.

[<span class="underline">40 U.S.C.
11331</span>](https://www.gpo.gov/fdsys/pkg/USCODE-2009-title40/pdf/USCODE-2009-title40-subtitleIII-chap113-subchapIII-sec11331.pdf),
“*Responsibilities for Federal Information Systems Standards*”

[<span class="underline">FISMA of
2014</span>](https://www.congress.gov/113/plaws/publ283/PLAW-113publ283.pdf),
“*The Federal Information Security Modernization Act of 2014*”

[<span class="underline">HSPD
12</span>](https://www.dhs.gov/homeland-security-presidential-directive-12),
“*Homeland Security Presidential Directive 12 – Policy for a Common
Identification Standard for Federal Employees and Contractors*”

[<span class="underline">OMB Circular No.
A-130</span>](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf),
“*Managing Information as a Strategic Resource*”

[<span class="underline">OMB
M-08-23</span>](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2008/m08-23.pdf),
“*Securing the Federal Government’s Domain Name System Infrastructure
(Submission of Draft Agency Plans Due by September 5, 2008)*”

[<span class="underline">OMB M
14-03</span>](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2014/m-14-03.pdf),
“*Enhancing the Security of Federal Information and Information
Systems*”

[<span class="underline">OMB
M-10-23</span>](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2010/m10-23.pdf),
“*Guidance for Agency Use of Third-Party Websites and Applications*”

[<span class="underline">OMB
M-15-13</span>](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2015/m-15-13.pdf),
“*Policy to Require Secure Connections across Federal Websites and Web
Services*”

[<span class="underline">OMB
M-17-12</span>](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2017/m-17-12_0.pdf),
“*Preparing for and Responding to a Breach of Personally Identifiable
Information*”

[<span class="underline">Privacy Act of
1974</span>](https://www.justice.gov/opcl/privacy-act-1974), “*5 USC, §
552a*”

[<span class="underline">OMB
Memoranda</span>](https://www.whitehouse.gov/omb/information-for-agencies/memoranda),
location of current fiscal year guidance on Federal Information Security
and Privacy Management Requirements, including FISMA reporting

## Federal Standards and Guidance:

The Contractor shall comply with all applicable Federal Information
Processing Standards (FIPS). NIST Special Publications (800 Series) are
guidance, unless required by a FIPS publication, in which case usage is
mandatory.

[<span class="underline">FIPS PUB
199</span>](http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.199.pdf),
“*Standards for Security Categorization of Federal Information and
Information Systems*”

[<span class="underline">FIPS PUB
200</span>](http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.200.pdf),
“*Minimum Security Requirements for Federal Information and
Information Systems*”

[<span class="underline">FIPS PUB
140-2</span>](http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.140-2.pdf),
“*Security Requirements for Cryptographic Modules*”

[<span class="underline">NIST SP 800-18, Revision
1</span>](http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-18r1.pdf),
“*Guide for Developing Security Plans for Federal Information Systems*”

[<span class="underline">NIST SP 800-30, Revision
1</span>](http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-30r1.pdf),
“*Guide for Conducting Risk Assessments*”

[<span class="underline">NIST SP 800-34, Revision
1</span>](http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-34r1.pdf),
“*Contingency Planning Guide for Federal Information Systems*”

[<span class="underline">NIST SP 800-37, Revision
1</span>](http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-37r1.pdf),
“*Guide for Applying the Risk Management Framework to Federal
Information Systems: A Security Lifecycle Approach*”

[<span class="underline">NIST SP
800-47</span>](http://csrc.nist.gov/publications/nistpubs/800-47/sp800-47.pdf),
“*Security Guide for Interconnecting Information Technology Systems*”

[<span class="underline">NIST SP 800-53, Revision
4</span>](http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r4.pdf),
“*Security and Privacy Controls for Federal Information Systems and
Organizations*”

[<span class="underline">NIST SP 800-53A, Revision
4</span>](http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53Ar4.pdf),
*“Assessing Security and Privacy Controls in Federal Information Systems
and Organizations: Building Effective Assessment Plans*”

[<span class="underline">NIST SP
800-63</span>](http://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63-3.pdf)-3,
“*Digital Identity Guidelines*”

[<span class="underline">NIST SP
800-122</span>](http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-122.pdf),
“*Guide to Protecting the Confidentiality of Personally Identifiable
Information (PII)*”

[<span class="underline">NIST SP
800-137</span>](http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-137.pdf),
“*Information Security Continuous Monitoring (ISCM) for Federal
Information Systems and Organizations*”

## GSA Policies:

The Contractor shall comply with the following GSA Directives/Policies.

  - > [<span class="underline">GSA Order CIO
    > 1878.1</span>](https://www.gsa.gov/directives-library/), “*GSA
    > Privacy Act Program*”

  - > [<span class="underline">GSA Order CIO
    > 1878.2</span>](https://www.gsa.gov/directives-library/),
    > “*Conducting Privacy Impact Assessments (PIAs) in GSA*”

  - > [<span class="underline">GSA Order CIO
    > 2100.1</span>](https://www.gsa.gov/directives-library/), “*GSA
    > Information Technology (IT) Security Policy*”

  - > [<span class="underline">GSA Order CIO
    > 9297.2</span>](https://www.gsa.gov/directives-library/), “*GSA
    > Information Breach Notification Policy*”

The GSA policies listed in this paragraph must be followed, if
applicable.

  - > [<span class="underline">GSA Order CIO
    > 2103.1</span>](https://www.gsa.gov/directives-library/),
    > “*Controlled Unclassified Information (CUI) Policy*”

  - > [<span class="underline">GSA Order CIO
    > 2104.1</span>](https://www.gsa.gov/directives-library/), “*GSA
    > Information Technology (IT) General Rules of Behavior*”

  - > [<span class="underline">GSA Order CIO
    > 2182.2</span>](https://www.gsa.gov/directives-library/),
    > “*Mandatory Use of Personal Identity Verification (PIV)
    > Credentials*”

## GSA Procedural Guides:

GSA IT Procedural Guides are guidance, unless required by a GSA
Directive/Policy, in which case usage is mandatory.

**Note:** GSA’s Procedural Guides are updated frequently; to make sure
you have the most recent version of publicly available procedural
guides, visit
[<span class="underline">GSA.gov</span>](https://www.gsa.gov/about-us/organization/office-of-the-chief-information-officer/chief-information-security-officer-ciso/it-security-procedural-guides).
If a non-publicly available guide is needed, contact the CO who will
coordinate with the GSA Office of the Chief Information Security Officer
to determine if it can be made
available.

## FIPS PUB 200 *Minimum Security Requirements for Federal Information and Information Systems* 

A mandatory federal standard that defines the minimum security
requirements for federal information and information systems in
seventeen security-related areas. Information systems supporting GSA
must meet the minimum security and privacy requirements through the use
of security controls in accordance with NIST Special Publication 800-53,
Revision 4 (hereafter described as NIST 800-53), *“Security and Privacy
Controls for Federal Information Systems and Organizations.”*

To comply with the Federal standard, GSA must determine the security
category of the information and information system in accordance with
FIPS PUB 199, *“Standards for Security Categorization of Federal
Information and Information Systems,”* and then the Contractor shall
apply the appropriately tailored set of Low, Moderate, or High impact
baseline security controls in NIST 800-53, as determined by GSA. NIST
800-53 controls requiring organization-defined parameters (i.e.,
password change frequency) shall be consistent with GSA specifications.
The GSA-specified control parameters and supplemental guidance defining
more specifically the requirements per FIPS PUB 199 impact level are
available in the GSA Control Tailoring Workbook referenced in Appendix A
of this document.

The Contractor shall use GSA technical guidelines, NIST guidelines,
Center for Internet Security (CIS) guidelines (Level 1), or industry
best practice guidelines in hardening their systems.

## Essential Security Controls

All NIST 800-53 controls must be implemented as per the applicable FIPS
PUB 199 Low, Moderate, or High baseline. The following table identifies
essential security controls from the respective baselines to highlight
their importance and ensure they are implemented. The Contractor shall
make the proposed system and security architecture of the information
system available to the Security Engineering Division, in the Office of
the Chief Information Security Officer for review and approval before
commencement of system build (architecture, infrastructure, and code).

<table>
<thead>
<tr class="header">
<th><strong>Control ID</strong></th>
<th><strong>Control Title</strong></th>
<th><strong>Baseline</strong></th>
<th><strong>GSA Implementation Guidance</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AC-2</td>
<td>Account Management</td>
<td>L, M, H</td>
<td></td>
</tr>
<tr class="even">
<td>AC-17 (3)</td>
<td>Remote Access | Managed Access Control Points</td>
<td>M, H</td>
<td>All remote accesses from internal users/systems to the external information system must be routed through GSA’s managed network access control points, subjecting them to security monitoring.</td>
</tr>
<tr class="odd">
<td>AU-2</td>
<td>Audit Events</td>
<td>L, M, H</td>
<td>Information systems shall implement audit configuration requirements as documented in applicable GSA IT Security Technical Hardening Guides (i.e., hardening and technology implementation guides); for web applications see GSA IT Security Procedural Guide 07-35, Section 2.8.10, What to Log. For technologies where a Technical Guide and Standard does not exist, events from an industry source such as Contractor guidance or Center for Internet Security benchmark, recommended by the GSA S/SO or Contractor to be approved and accepted by the GSA AO shall be used.</td>
</tr>
<tr class="even">
<td>CM-6</td>
<td>Configuration Settings</td>
<td>L, M, H</td>
<td>Information systems, including Contractor owned/operated systems on behalf of GSA, shall configure their systems in agreement with GSA technical guidelines, NIST guidelines, Center for Internet Security guidelines (Level 1), or industry best practice guidelines, as deemed appropriate.</td>
</tr>
<tr class="odd">
<td>CP-7</td>
<td>Alternative Processing Site</td>
<td>M, H</td>
<td>FIPS PUB 199 Moderate and High impact systems must implement processing across geographically-disparate locations to ensure fault tolerance. Amazon Web Services based architectures must implement a multi-region strategy (multiple availability zones in a single region are not sufficient).</td>
</tr>
<tr class="even">
<td>CP-8</td>
<td>Telecom Services</td>
<td>M, H</td>
<td>FIP PUB 199 Moderate and High impact information systems must implement alternate telecom services to support resumption when the primary telecommunications capabilities are unavailable at either the primary or alternate processing or storage sites.</td>
</tr>
<tr class="odd">
<td>IA-2 (1)</td>
<td>Identification and Authentication (Organizational Users) | Network Access to Privileged Accounts</td>
<td>L, M, H</td>
<td>All information systems shall implement multi-factor authentication for privileged accounts.</td>
</tr>
<tr class="even">
<td>IA-2 (2)</td>
<td>Identification and Authentication (Organizational Users) | Network Access to Non-Privileged Accounts</td>
<td>M, H</td>
<td>FIPS PUB 199 Moderate and High impact information systems must implement multi-factor authentication for non-privileged accounts.</td>
</tr>
<tr class="odd">
<td>IA-7</td>
<td>Cryptographic Module Authentication</td>
<td>L, M, H</td>
<td><p>The information system shall implement FIPS PUB 140-2 compliant encryption modules for authentication functions. Reference:</p>
<p><span class="underline">https://csrc.nist.gov/Projects/Cryptographic-Module-Validation-Program/Validated-Modules</span></p></td>
</tr>
<tr class="even">
<td>MP-4</td>
<td>Media Storage</td>
<td>M, H</td>
<td>Digital media including magnetic tapes, external/removable hard drives, flash/thumb drives, diskettes, compact disks and digital video disks shall be encrypted using a FIPS PUB 140-2 certified encryption module.</td>
</tr>
<tr class="odd">
<td>MP-5</td>
<td>Media Transport</td>
<td>M, H</td>
<td>Digital media including magnetic tapes, external/removable hard drives, flash/thumb drives and digital video disks shall be encrypted using a FIPS PUB 140-2 certified encryption module during transport outside of controlled areas.</td>
</tr>
<tr class="even">
<td>PL-8</td>
<td>Information Security Architecture</td>
<td>M, H</td>
<td>All information system security architectures must be formally reviewed and approved by the Office of the Chief Information Security Officer, Security Engineering Division during the system develop/design stages of the SDLC and prior to Security Assessment and Authorization.</td>
</tr>
<tr class="odd">
<td>RA-5</td>
<td>Vulnerability Scanning</td>
<td>L, M, H</td>
<td><p>All systems must complete weekly operating system (OS) and monthly web application vulnerability scans.</p>
<p>The most recent vulnerability scanning results shall be provided to GSA together with the quarterly POA&amp;M submission.</p></td>
</tr>
<tr class="even">
<td>SA-22</td>
<td>Unsupported System Components</td>
<td><p>GSA</p>
<p>Required</p></td>
<td>All systems must be comprised of software and hardware components that are fully supported in terms of security patching for the anticipated life of the system; software must be on GSA’s Enterprise Architecture IT Standards List.</td>
</tr>
<tr class="odd">
<td>SC-8 / SC-8(1)</td>
<td>Transmission Confidentiality and Integrity / Transmission Confidentiality and Integrity | Cryptographic or Alternate Physical Protection</td>
<td>M, H</td>
<td><p>Implemented encryption algorithms and cryptographic modules shall be FIPS-approved and FIPS PUB 140-2 validated, respectively.</p>
<blockquote>
<p>o Digital signature encryption algorithms - Reference: <span class="underline">https://csrc.nist.gov/Projects/Cryptographic-Algorithm-Validation-Program/Validation/Validation-List/DSA</span></p>
<p>o Block cypher encryption algorithms - Reference: <span class="underline">https://csrc.nist.gov/Projects/Cryptographic-Algorithm-Validation-Program/Block-Ciphers</span></p>
<p>o Secure hashing algorithms – Reference: <span class="underline">https://csrc.nist.gov/Projects/Cryptographic-Algorithm-Validation-Program/Secure-Hashing</span></p>
</blockquote>
<p>Internet accessible Websites shall implement HTTPS Only and <a href="https://https.cio.gov/hsts/"><span class="underline">HTTP Strict Transport Security</span></a> (HSTS), reference OMB Memorandum M-15-13.</p>
<p>SSL/TLS implementations shall align with GSA IT Security Procedural Guide 14-69, <em>“SSL/TLS Implementation.”</em></p></td>
</tr>
<tr class="even">
<td>SC-13</td>
<td>Cryptographic Protection</td>
<td>L, M, H</td>
<td><p>Implemented encryption algorithms and cryptographic modules shall be FIPS-approved and FIPS PUB 140-2 validated, respectively.</p>
<blockquote>
<p>o Digital signature encryption algorithms - Reference: <span class="underline">https://csrc.nist.gov/Projects/Cryptographic-Algorithm-Validation-Program/Validation/Validation-List/DSA</span></p>
<p>o Block cypher encryption algorithms - Reference: <span class="underline">https://csrc.nist.gov/Projects/Cryptographic-Algorithm-Validation-Program/Block-Ciphers</span></p>
<p>o Secure hashing algorithms – Reference: <span class="underline">https://csrc.nist.gov/Projects/Cryptographic-Algorithm-Validation-Program/Secure-Hashing</span></p>
</blockquote></td>
</tr>
<tr class="odd">
<td>SC-17</td>
<td>PKI Certificates</td>
<td>M, H</td>
<td>Implement appropriate creation, use, and signing of crypto certs in agreement with GSA IT Security Procedural Guide 14-69, <em>“SSL/TLS Implementation,”</em> and NIST Special Publications 800-32, NIST 800-63.</td>
</tr>
<tr class="even">
<td>SC-18</td>
<td>Mobile Code</td>
<td>M, H</td>
<td></td>
</tr>
<tr class="odd">
<td>SC-22</td>
<td>Architecture and Provisioning for Name / Address Resolution Service</td>
<td>L, M, H</td>
<td>Information systems shall be Domain Name System Security Extensions (DNSSEC) compliant. Reference OMB Memorandum M-08-23, which requires all Federal Government departments and agencies that have registered and are operating second level .gov to be DNSSEC.</td>
</tr>
<tr class="even">
<td>SC-28 (1)</td>
<td>Protection of Information at Rest | Cryptographic Protection</td>
<td>GSA Required – For systems with Personally Identifiable Information Only</td>
<td>Systems bearing PII must implement protect information at rest. At a minimum, fields bearing PII data must be encrypted with field level encryption. Encryption algorithms shall be FIPS-approved; implemented encryption modules shall be FIPS PUB 140-2 validated.</td>
</tr>
<tr class="odd">
<td>SI-2</td>
<td>Flaw Remediation</td>
<td>L, M, H</td>
<td>All projects and systems must be adequately tested for flaws; all Critical, High, and Moderate risk findings must be remediated prior to go-live. Post go-live, all critical and high vulnerabilities identified must be mitigated within 30 days and all moderate vulnerabilities mitigated within 90 days.</td>
</tr>
<tr class="even">
<td>SI-3</td>
<td>Malicious Code Protection</td>
<td>L, M, H</td>
<td></td>
</tr>
<tr class="odd">
<td>SI-4</td>
<td>Information System Monitoring</td>
<td>L, M, H</td>
<td></td>
</tr>
<tr class="even">
<td>SI-10</td>
<td>Information Input Validation</td>
<td>M, H</td>
<td>All system accepting input from end users must validate the input in accordance to industry best practices and published guidelines, including GSA IT Security Procedural Guide 07-35, <em>“Web Application Security,”</em> and OWASP Top 10 Web Application Security Vulnerabilities.</td>
</tr>
<tr class="odd">
<td>AR-2</td>
<td>Privacy Impact and Risk Assessment</td>
<td>See note below</td>
<td>The Contractor shall conduct a Privacy Threshold Analysis (PTA) and, if applicable, a Privacy Impact Assessment (PIA) identifying the categories of information and addressing potential risks to PII. The Contractor also shall coordinate with the GSA Privacy Office concerning these documents.</td>
</tr>
<tr class="even">
<td>AR-8</td>
<td>Accounting of Disclosures</td>
<td>See note below</td>
<td>The Contractor shall keep an accurate accounting of disclosures of information held in any system of records under its control.</td>
</tr>
<tr class="odd">
<td>TR-2</td>
<td>System of Records Notices and Privacy Act Statements</td>
<td>See note below.</td>
<td>The Contractor shall coordinate with the GSA Privacy Office to ensure System of Records Notices (SORNs) and Privacy Act notices on forms that collect Personally Identifiable Information (PII) are established and kept current.</td>
</tr>
<tr class="even">
<td>UL-1</td>
<td>Internal Use</td>
<td>See note below</td>
<td>The Contractor shall ensure that PII is shared internally only for the authorized purpose(s) identified in the Privacy Act and/or in public notices.</td>
</tr>
<tr class="odd">
<td>UL-2</td>
<td>Information Sharing with Third Parties</td>
<td>See note below</td>
<td>The Contractor shall coordinate with the GSA Privacy Office to ensure PII is shared in accordance with GSA requirements and agreements with third parties.</td>
</tr>
</tbody>
</table>

**Note:** Privacy controls are not associated with a baseline. Controls
are applicable/not applicable based on PII data being collected, stored,
or transmitted.

## Assessment and Authorization (A\&A) Activities

The implementation of a new Federal Government IT system requires a
formal approval process known as Assessment and Authorization (A\&A).
NIST Special Publication 800-37, Revision 1 (hereafter described as NIST
800-37) and GSA IT Security Procedural Guide 06-30, “*Managing
Enterprise Risk,*” provide guidelines for performing the A\&A process.
The Contractor system/application must have a valid assessment and
authorization, known as an Authority to Operate (ATO) (signed by the
Federal Government) before going into operation and processing GSA
information. The failure to obtain and maintain a valid ATO will result
in the termination of the contract. The system must have a new A\&A
conducted (signed by the Federal Government) at least every three (3)
years or at the discretion of the Authorizing Official when there is a
significant change to the system’s security posture or via continuous
monitoring based on GSA CIO IT Security 12-66, “*Information Security
Continuous Monitoring Strategy*” that is reviewed and accepted by the
GSA CISO.

### Assessing the System

1.  > The Contractor shall comply with Assessment and Authorization
    > (A\&A) requirements as mandated by Federal laws and policies,
    > including making available any documentation, physical access, and
    > logical access needed to support this requirement. The Level of
    > Effort for the A\&A is based on the System’s NIST Federal
    > Information Processing Standard (FIPS) Publication 199
    > categorization. The Contractor shall create, maintain and update
    > the following A\&A documentation:

<!-- end list -->

  - > System Security Plan (SSP) completed in agreement with NIST
    > Special Publication 800-18, Revision 1, *“Guide for Developing
    > Security Plans for Federal Information Systems.*” The SSP shall
    > include as appendices required policies and procedures across 17
    > control families mandated per FIPS PUB 200, Rules of Behavior, and
    > Interconnection Agreements (in agreement with NIST Special
    > Publication 800-47, *“Security Guide for Interconnecting
    > Information Technology Systems”*). The SSP shall include; as an
    > appendix, a completed GSA Control Tailoring Workbook identified in
    > Appendix A of this guide. The column in the workbook titled “GSA
    > Defined Values,” shall be used to document all Contractor
    > implemented settings that are different from the GSA defined
    > setting and where the GSA defined setting allows a Contractor
    > determined setting.

  - > Contingency Plan (including Disaster Recovery Plan) completed in
    > agreement with NIST Special Publication 800-34.

  - > Contingency Plan Test Report completed in agreement with GSA IT
    > Security Procedural Guide 06-29, *“Contingency Planning.”*

  - > Incident Response Plan completed in agreement with NIST Special
    > Publication 800-61, “Computer Security Incident Handling Guide”
    > and GSA IT Security Procedural Guide 01-02, “*Incident Response*.”

  - > Incident Response Test Report completed in agreement NIST Special
    > Publication 800-61, “Computer Security Incident Handling Guide”
    > and GSA IT Security Procedural Guide 01-02, “*Incident Response*.”

  - > Configuration Management Plan completed in agreement with GSA IT
    > Security Procedural Guide 01-05, “*Configuration Management*.”

  - > Plan of Actions & Milestones completed in agreement with GSA IT
    > Security Procedural Guide 09-44, *“Plan of Action and Milestones
    > (POA\&M).”*

  - > Penetration Test Reports documenting the results of vulnerability
    > analysis and exploitability of identified vulnerabilities. Note:
    > Penetration testing is required for all FIPS PUB 199 Low impact
    > and Moderate impact Internet accessible information systems, and
    > all FIPS PUB 199 High impact information systems are required to
    > complete an independent penetration test and provide an
    > Independent Penetration Test Report documenting the results of the
    > exercise as part of the A\&A package. Reference GSA IT Security
    > Procedural Guide 06-30, *“Managing Enterprise Risk”* and GSA IT
    > Security Procedural Guide 11-51, *“Conducting Penetration Test
    > Exercises”* for penetration testing guidance.

<!-- end list -->

2.  > Information systems must be assessed and authorized every three
    > (3) years or whenever there is a significant change to the
    > system's security posture in accordance with NIST Special
    > Publication 800-37, Revision 1, *"Guide for the Security
    > Certification and Accreditation of Federal Information Systems,"*
    > and CIO IT Security 06-30, "*Managing Enterprise Risk*" or via
    > continuous monitoring based on GSA CIO IT Security 12-66,
    > "*Information Security Continuous Monitoring Strategy*" that is
    > reviewed and accepted by the GSA CISO.

3.  > At the Moderate impact level and higher, the Government is
    > responsible for providing an independent Security Assessment/Risk
    > Assessment in accordance with GSA IT Security Procedural Guide
    > 06-30, *“Managing Enterprise Risk.”*

4.  > If the Government is responsible for providing a Security
    > Assessment/Risk Assessment and Penetration Test, the Contractor
    > shall allow GSA employees (or GSA designated third party
    > Contractors) to conduct A\&A activities to include control reviews
    > in accordance with NIST 800-53/NIST 800-53A and GSA IT Security
    > Procedural Guide 06-30, *“Managing Enterprise Risk.”* Review
    > activities include but are not limited to operating system
    > vulnerability scanning, web application scanning, and database
    > scanning of applicable systems that support the processing,
    > transportation, storage, or security of GSA information. This
    > includes the general support system infrastructure.

5.  > Identified gaps between required NIST 800-53 controls and the
    > Contractor’s implementation as documented in the Security
    > Assessment/Risk Assessment report shall be tracked for mitigation
    > in a Plan of Action and Milestones (POA\&M) document completed in
    > accordance with GSA IT Security Procedural Guide 09-44, *“Plan of
    > Action and Milestones (POA\&M).”* Depending on the severity of the
    > gaps, the Government may require them to be remediated before an
    > Authorization to Operate is issued.

6.  > The Contractor is responsible for mitigating all security risks
    > found during the A\&A and continuous monitoring activities. All
    > high-risk vulnerabilities must be mitigated within 30 days and all
    > moderate risk vulnerabilities must be mitigated within 90 days
    > from the date vulnerabilities are formally identified. The
    > Government will determine the risk rating of vulnerabilities.

### Authorization of the System

1.  > Upon receipt of the documentation (Security Authorization Package
    > (SAP)) described in GSA IT Security Procedural Guide 06-30,
    > *“Managing Enterprise Risk”* and NIST Special Publication 800-37
    > as documented above, the GSA Authorizing Official (AO) for the
    > system (in coordination with the GSA Chief Information Security
    > Officer (CISO), system GSA TTS Product Owner, Information System
    > Security Manager (ISSM), and Information System Security Officer
    > (ISSO) will render an authorization decision to:

<!-- end list -->

  - > Authorize system operation w/out any restrictions or limitations
    > on its operation;

  - > Authorize system operation w/restriction or limitation on its
    > operation, or;

  - > Not authorize for operation.

<!-- end list -->

2.  > The Contractor shall provide access to the Federal Government, or
    > their designee acting as their agent, when requested, in order to
    > verify compliance with the requirements for an Information
    > Technology security program. At its option, the Government may
    > choose to conduct on site surveys. The Contractor shall make
    > appropriate personnel available for interviews and documentation
    > during this review. If documentation is considered proprietary or
    > sensitive, these documents may be reviewed on-site under the
    > hosting Contractor’s supervision.

## Reporting and Continuous Monitoring

Maintenance of the security authorization to operate will be through
continuous monitoring of security controls of the external system and
its environment of operation to determine if the security controls in
the information system continue to be effective over time in light of
changes that occur in the system and environment. Through continuous
monitoring, security controls and supporting deliverables are updated
and submitted to GSA per the schedules below. The submitted deliverables
(or lack thereof) provide a current understanding of the security state
and risk posture of the information systems. They allow GSA AOs to make
credible risk-based decisions regarding the continued operations of the
information systems and initiate appropriate responses as needed when
changes occur.

### Deliverables to be provided to the GSA COR/ISSO/ISSM Quarterly

1.  > Vulnerability Scanning - Reference: NIST 800-53 control RA-5

<!-- end list -->

  - > Provide the most recent Web Application and Operating System
    > vulnerability scan reports.

<!-- end list -->

2.  > Plan of Action & Milestones (POA\&M) Update - Reference: NIST
    > 800-53 control CA-5

<!-- end list -->

  - > Provide POA\&M updates in accordance with requirements and the
    > schedule set forth in GSA CIO IT Security Procedural Guide 09-44,
    > “Plan of Action and Milestones
    (POA\&M).”

### Deliverables to be provided to the GSA COR/ISSO/ISSM Annually

1.  #### Updated A\&A documentation including the System Security Plan and Contingency Plan
    
    1.  #### System Security Plan - Reference: NIST 800-53 control PL-2

#### Review and update the System Security Plan annually to ensure the plan is current and accurately describes implemented system controls and reflects changes to the Contractor system and its environment of operation. The System Security Plan must be in accordance with NIST 800-18, Revision 1, *“Guide for Developing Security Plans.”*

#### Contingency Plan - Reference: NIST 800-53 control CP-2

> Provide an annual update to the contingency plan completed in
> accordance with NIST 800-34, *“Contingency Planning
Guide.”*

#### User Certification/Authorization Review Documents - Reference: NIST 800-53 control AC-2

#### Provide the results of the annual review and validation of system users’ accounts to ensure the continued need for system access. The user certification and authorization documents will illustrate the organization establishes, activates, modifies, reviews, disables, and removes information system accounts in accordance with documented account management procedures.

#### Separation of Duties Matrix - Reference: NIST 800-53 control AC-5

> Develop and furnish a separation of duties matrix reflecting proper
> segregation of duties for IT system maintenance, management, and
> development processes. The separation of duties matrix will be updated
> or reviewed on an annual
basis.

#### Information Security Awareness and Training Records - Reference: NIST 800-53 control AT-4

> Provide the results of security awareness (AT-2) and role-based
> information security technical training (AT-3). AT-2 requires basic
> security awareness training for employees and Contractors that support
> the operation of the Contractor system. AT‑3 requires information
> security technical training to information system security roles.
> Training shall be consistent with the requirements contained in C.F.R.
> Part 5 Subpart C (5 C.F.R 930.301) and conducted at least annually.

#### Annual FISMA Self-Assessment - Reference: NIST 800-53 control CA-2

> Deliver the results of the annual FISMA self-assessment conducted per
> GSA IT Security Procedural Guide 04-26, “*Federal Information Security
> Modernization Act (FISMA) Implementation.”* Based on the controls
> selected for self-assessment, the GSA OCISO will provide the
> appropriate test cases for
completion.

#### System(s) Baseline Configuration Standard Document - Reference: NIST 800-53 control CM-2/CM-2(1)

> Provide a well-defined, documented, and up-to-date specification to
> which the information system is
built.

#### System Configuration Settings Verification - Reference: NIST 800-53 control CM-6/CM-6(1)

> Establish and document mandatory configuration settings for
> information technology products employed within the information system
> that reflect the most restrictive mode consistent with operational
> requirements. Configuration settings are the configurable
> security-related parameters of information technology products that
> compose the information system. Systems should be configured in
> agreement with GSA technical guidelines, NIST guidelines, Center for
> Internet Security guidelines (Level 1), or industry best practice
> guidelines in hardening their systems, as deemed appropriate by the
> Authorizing Official.
> 
> Provide the most recent operating system Configuration Settings
> Compliance scan report.

#### Configuration Management Plan - Reference: NIST 800-53 control CM-9

> Provide an annual update to the Configuration Management Plan for the
> information system.

#### Contingency Plan Test Report - Reference: NIST 800-53 control CP-4

> Provide a contingency plan test report completed in accordance with
> GSA IT Security Procedural Guide 06-29, *“Contingency Planning.”* A
> continuity test shall be conducted annually prior to mid-July of each
> year. The continuity test can be a table top test while the system is
> at the FIPS PUB 199 Low Impact level. The table top test must include
> Federal and hosting Contractor representatives. Functional exercises
> must be completed once every three years for FIPS PUB 199 Moderate
> impact systems and annually for FIPS PUB 199 High impact systems.

#### Incident Response Test Report - Reference: NIST 800-53 control IR-3

> Provide an incident response plan test report documenting results of
> incident reporting process per GSA IT Security Procedural Guide 01-02,
> *“Incident
Response.”*

#### Information System Interconnection Agreements - Reference: NIST 800-53 control CA-3

> Provide Interconnection Security Agreements (ISA) and supporting
> Memoranda of Agreement/Understanding (MOA/U), completed in accordance
> with NIST 800-47, *“Security Guide for Connecting Information
> Technology Systems,”* for existing and new interconnections. Per NIST
> 800-47, an interconnection is the <span class="underline"> </span>
> direct connection of two or more IT systems for the purpose of sharing
> data and other information resources through a pipe, such as ISDN, T1,
> T3, DS3, VPN, etc. ISAs shall be submitted as appendices as part of
> the annual System Security Plan submission. ISAs shall include, if
> applicable, any changes since the last submission; updated ISAs are
> required at least every three years.

#### Rules of Behavior - Reference: NIST 800-53 control PL-4

> Define and establish Rules of Behavior for information system users.
> Rules of Behavior shall be submitted as an appendix to the System
> Security Plan.

#### Penetration Testing Report - Reference: NIST 800-53 control CA-8

> All Internet accessible systems, and all FIPS PUB 199 High impact
> systems are required to complete an independent penetration test and
> provide a Penetration Test Report documenting the results of the
> exercise as part of their A\&A package. Annual penetration tests are
> required for these same systems in accordance with GSA Order CIO
> 2100.1 and CIO-IT Security-11-51, “*Conducting Penetration Test
> Exercises.*”

#### Personnel Screening and Security - Reference: NIST 800-53 control PS-3, NIST 800-53 control PS-7

> Furnish documentation reflecting favorable adjudication of background
> investigations for all personnel (including subContractors) supporting
> the system. Contractors shall comply with GSA Order CIO 2100.1, *“GSA
> Information Technology (IT) Security Policy”* and GSA Order*,* CIO P
> 2181.1, “*Homeland Security Presidential Directive-12 (HSPD-12)
> Personal Identity Verification and Credentialing Handbook*.” GSA
> separates the risk levels for personnel working on Federal computer
> systems into three categories: Low Risk, Moderate Risk, and High Risk.

  - > Those contract personnel (hereafter known as “Applicant”)
    > determined to be in a Low Risk position will require a National
    > Agency Check with Written Inquiries (NACI) investigation.

  - > Those Applicants determined to be in a Moderate Risk position will
    > require either a Limited Background Investigation (LBI) or a
    > Minimum Background Investigation (MBI) based on the CO’s
    > determination.

  - > Those Applicants determined to be in a High Risk position will
    > require a Background Investigation (BI).

> Applicants will not be reinvestigated if a prior favorable
> adjudication is on file with FPS or GSA, there has been less than a
> one year break in service, and the position is identified at the same
> or lower risk level.
> 
> Once a favorable FBI Criminal History Check (Fingerprint Check) has
> been returned, Applicants may receive a GSA identity credential (if
> required) and initial access to GSA information systems. The HSPD-12
> Handbook contains procedures for obtaining identity credentials and
> access to GSA information systems as well as procedures to be followed
> in case of unfavorable adjudications.

### Deliverables to be provided to the GSA COR/ISSO/ISSM Biennially

#### Policies and Procedures

> Develop and maintain current the following policies and procedures:

1.  > Access Control Policy and Procedures (NIST 800-53 AC-1)

2.  > Security Awareness and Training Policy and Procedures (NIST 800-53
    > AT-1)

3.  > Audit and Accountability Policy and Procedures (NIST 800-53 AU-1)

4.  > Identification and Authentication Policy and Procedures (NIST
    > 800-53 IA-1)

5.  > Incident Response Policy and Procedures (NIST 800-53 IR-1,
    > reporting timeframes are documented in GSA IT Security Procedural
    > Guide 01-02, “*Incident Response*”

6.  > System Maintenance Policy and Procedures (NIST 800-53 MA-1)

7.  > Media Protection Policy and Procedures (NIST 800-53 MP-1)

8.  > Physical and Environmental Policy and Procedures (NIST 800-53
    > PE-1)

9.  > Personnel Security Policy and Procedures (NIST 800-53 PS-1)

10. > System and Information Integrity Policy and Procedures (NIST
    > 800-53 SI-1)

11. > System and Communication Protection Policy and Procedures (NIST
    > 800-53 SC-1)

12. > Key Management Policy (NIST 800-53 SC-12)

## GSA Privacy Requirements

<span class="underline">[Personally identifiable information
(PII)](https://www.gsa.gov/portal/content/104256)</span> is not in the
scope of the acquisition and PII is not expected to be stored,
processed, or transmitted in the Contractor's information system. The
collection, maintenance or dissemination of any PII that is subject to
the Privacy Act and/or the E-Government Act will be handled in full
accordance with all GSA rules of conduct and in accordance with GSA
Privacy Program requirements.

The Contractor shall prepare a Privacy Threshold Analysis (PTA) to
confirm and document PII is not in scope, or to determine which
categories of information will be stored, processed, or transmitted by
the system. The PTA must be completed before development begins and
whenever a change with a privacy impact (e.g., a new category of
information is collected) is made to an existing system. PTAs are
required as part of GSA’s process to determine whether a Privacy Impact
Assessment (PIA) and/or a System of Records Notice (SORN) is required,
and if any other privacy requirements apply to the information system.
Instructions for the PTA and PIA forms can be found at
https://www.gsa.gov/reference/gsa-privacy-program/privacy-impact-assessments-pia.

PII (should it come into scope) will require the following guidelines be
adhered to.

  - > The Contractor’s information system must be authorized at least at
    > the FIPS PUB 199 Moderate level.

  - > For any system that collects, maintains or disseminates PII, a PIA
    > must be completed by the Contractor and provided to the GSA
    > Privacy Office for review along with the other authorization to
    > operate (ATO) documents.

  - > If the system retrieves information using PII, the Privacy Act
    > applies and it must have a system of records notice (SORN)
    > published in the Federal Register.

  - > If PII is collected from individuals by the system, a Privacy Act
    > Statement (i.e., Privacy Notice) must be provided to users prior
    > to their use of the application on what data is being collected
    > and why, as well as the authority for the collection and the
    > impact of not providing some or all of it. The Privacy Act
    > Statement must be available to the individual directly on the form
    > used to collect the information. Providing a link back to the
    > Statement from the form is acceptable.

Provided below is a template for an acceptable Privacy Act Statement,
when bracketed sections are completed. A completed example is available
at
[<span class="underline">https://www.gsa.gov/reference/gsa-privacy-program/privacy-act-statement-for-design-research</span>](https://www.gsa.gov/reference/gsa-privacy-program/privacy-act-statement-for-design-research).

All Contractor staff who have significant privacy information
responsibilities must complete GSA’s specialized Privacy 201 Training.
This includes Contractors who work with PII as part of their work
duties.

## Additional Compliance Stipulations

1.  > Deliverables shall be labeled Sensitive But Unclassified (SBU) or
    > Contractor selected designation per document sensitivity. External
    > transmission/dissemination of SBU to or from a Government computer
    > must be encrypted. Certified encryption modules must be used in
    > accordance with FIPS PUB 140-2, *“Security Requirements for
    > Cryptographic Modules.”*

2.  > The Contractor shall certify applications are fully functional and
    > operate correctly as intended on systems using the United States
    > Government Configuration Baseline (USGCB). This includes Internet
    > Explorer configured to operate on Windows. The standard
    > installation, operation, maintenance, update, and/or patching of
    > software shall not alter the configuration settings from the
    > approved USGCB configuration. The information technology should
    > also use the Windows Installer Service for installation to the
    > default “program files” directory and should be able to silently
    > install and uninstall. Applications designed for normal end users
    > shall run in the standard user context without elevated system
    > administration privileges. The Contractor shall use Security
    > Content Automation Protocol (SCAP) validated tools with USGCB
    > Scanner capability to certify their products operate correctly
    > with USGCB configurations and do not alter USGCB settings.

3.  > The Contractor shall cooperate in good faith in defining
    > non-disclosure agreements that other third parties must sign when
    > acting as the Federal government’s agent.

4.  > The Government has the right to perform manual or automated
    > audits, scans, reviews, or other inspections of the Contractor’s
    > IT environment being used to provide or facilitate services for
    > the Government. The Contractor shall be responsible for the
    > following privacy and security safeguards:
    
    1.  > The Contractor shall not publish or disclose in any manner,
        > without the COs written consent, the details of any safeguards
        > either designed or developed by the Contractor under this
        > contract or otherwise provided by the Government. Exception -
        > Disclosure to a Consumer Agency for purposes of A\&A
        > verification or to the MAX.Gov portal. To the extent required
        > to carry out a program of inspection to safeguard against
        > threats and hazards to the security, integrity, and
        > confidentiality of Government data, the Contractor shall
        > afford the Government access to the Contractor’s facilities,
        > installations, technical capabilities, operations,
        > documentation, records, and databases within 72 hours of the
        > request. Access to support incident investigations, shall be
        > provided as soon as possible but not longer than 72 hours
        > after request.  
        >   
        > The program of inspection shall include, but is not limited
        > to:
        
          - > Authenticated and unauthenticated operating system/network
            > vulnerability scans
        
          - > Authenticated and unauthenticated web application
            > vulnerability scans
        
          - > Authenticated and unauthenticated database application
            > vulnerability scans
        
          - > Automated scans can be performed by Government personnel,
            > or agents acting on behalf of the Government, using
            > Government operated equipment, and Government specified
            > tools. If the Contractor chooses to run its own automated
            > scans or audits, results from these scans may at the
            > Government’s discretion, be accepted in lieu of Government
            > performed vulnerability scans. In these cases, scanning
            > tools and their configuration shall be approved by the
            > Government. In addition, the results of
            > Contractor-conducted scans shall be provided in full to
            > the Government.
    
    2.  > If new or unanticipated threats or hazards are discovered by
        > either the Government or the Contractor, or if existing
        > safeguards have ceased to function, the discoverer shall
        > immediately bring the situation to the attention of the other
        > party.

5.  > The Contractor shall comply with Section 1634 of
    > [<span class="underline">Public Law
    > 115-91</span>](https://www.congress.gov/bill/115th-congress/house-bill/2810/text#toc-HC791755DF28D4E2BA0A5C4418094E922)
    > that prohibits use of any hardware, software, or services
    > developed or provided, in whole or in part, by— (1) Kaspersky Lab
    > (or any successor entity); (2) any entity that controls, is
    > controlled by, or is under common control with Kaspersky Lab; or
    > (3) any entity of which Kaspersky Lab has majority ownership.

# Clauses

Applicable clauses from the GSA Schedule 70 Contract automatically flow
down at the Task Order level.

## Contract Clauses Incorporated by Reference

**FAR 52.252-1 - Solicitation Provisions Incorporated by Reference (Feb
1998)**

This solicitation incorporates one or more solicitation provisions by
reference, with the same force and effect as if they were given in full
text. Upon request, the Contracting Officer will make their full text
available. The offeror is cautioned that the listed provisions may
include blocks that must be completed by the offeror and submitted with
its quotation or offer. In lieu of submitting the full text of those
provisions, the offeror may identify the provision by paragraph
identifier and provide the appropriate information with its quotation or
offer. Also, the full text of a solicitation provision may be accessed
electronically at this/these address(es):

Federal Acquisition Regulation:
[<span class="underline">https://www.acquisition.gov/far/current/html/FARTOCP52.html</span>](https://www.acquisition.gov/far/current/html/FARTOCP52.html)

GSA Acquisition Manual:
[<span class="underline">https://www.acquisition.gov/?q=browsegsam</span>](https://www.acquisition.gov/?q=browsegsam)

**FAR 52.252-2 Clauses Incorporated by Reference (Feb 1998)**

This contract incorporates one or more clauses by reference, with the
same force and effect as if they were given in full text. Upon request,
the Contracting Officer will make their full text available. Also, the
full text of a clause may be accessed electronically at this/these
address(es):
([<span class="underline">https://www.acquisition.gov/browsefar</span>](https://www.acquisition.gov/browsefar))

**FAR 52.224-1** Privacy Act Notification (Apr 1984**)**

**FAR 52.224-2** Privacy Act (Apr 1984)

**FAR 52.239-1** Privacy or Security Safeguards (Aug. 1996)

**GSAR 552.212-4** Contract Terms and Conditions—Commercial Items Nov
2009

Alternate II (July 2015)(DEVIATION FAR 52.212-4)

**GSAR 552.232-39** Unenforceability of Unauthorized Obligations. (FAR
Deviation Feb 2018)

**FAR 52.203-19 -** Prohibition on Requiring Certain Internal
Confidentiality Agreements or Statements (Jan 2017)

**FAR 52.204-21** Basic Safeguarding of Covered Contractor Information
Systems

**FAR 52.212-4 -** Contract Terms and Conditions - Commercial items (JAN
2017)

**52.217-7 - Option for Increased Quantity—Separately Priced Line Item
(Mar 1989)**  
The Government may require the delivery of the numbered line item,
identified in the Schedule as an option item, in the quantity and at the
price stated in the Schedule. The Contracting Officer may exercise the
option by written notice to the Contractor within \[insert in the clause
the period of time in which the Contracting Officer has to exercise the
option\]. Delivery of added items shall continue at the same rate that
like items are called for under the contract, unless the parties
otherwise agree.

**FAR 52.217-8 - Option to Extend Services (Nov 1999)**

The Government may require continued performance of any services within
the limits and at the rates specified in the contract. These rates may
be adjusted only as a result of revisions to prevailing labor rates
provided by the Secretary of Labor. The option provision may be
exercised more than once, but the total extension of performance
hereunder shall not exceed 6 months. The Contracting Officer may
exercise the option by written notice to the Contractor before the
contract expires.

**FAR 52.217-9 - Option to Extend the Term of the Contract (Mar 2000)**

(a) The Government may extend the term of this contract by written
notice to the Contractor within 5 days provided that the Government
gives the Contractor a preliminary written notice of its intent before
the contract expires. The preliminary notice does not commit the
Government to an extension.

(b) If the Government exercises this option, the extended contract shall
be considered to include this option clause.

(c) The total duration of this contract, including the exercise of any
options under this clause, shall not exceed 2 years.

**GSAM 552.217-71 - Notice Regarding Option(s) (Nov 1992)**

The General Services Administration (GSA) has included an option to
extend the term of this contract in order to demonstrate the value it
places on quality performance by providing a mechanism for continuing a
contractual relationship with a successful Offeror that performs at a
level which meets or exceeds GSA’s quality performance expectations as
communicated to the Contractor, in writing, by the Contracting Officer
or designated representative. When deciding whether to exercise the
option, the Contracting Officer will consider the quality of the
Contractor’s past performance under this contract in accordance with 48
CFR 517.207.

**52.203-18 – Prohibition on Contracting with Entities that Require
Certain Internal Confidentiality Agreements or
Statements--Representation (Jan 2017)**

(a) Definition. As used in this provision--

“Internal confidentiality agreement or statement”, “subcontract”, and
“subContractor”, are defined in the clause at 52.203-19, Prohibition
on Requiring Certain Internal Confidentiality Agreements or Statements.

(b) In accordance with section 743 of Division E, Title VII, of the
Consolidated and Further Continuing Appropriations Act, 2015 (Pub. L.
113-235) and its successor provisions in subsequent appropriations acts
(and as extended in continuing resolutions), Government agencies are not
permitted to use funds appropriated (or otherwise made available) for
contracts with an entity that requires employees or subContractors of
such entity seeking to report waste, fraud, or abuse to sign internal
confidentiality agreements or statements prohibiting or otherwise
restricting such employees or subContractors from lawfully reporting
such waste, fraud, or abuse to a designated investigative or law
enforcement representative of a Federal department or agency authorized
to receive such information.

(c) The prohibition in paragraph (b) of this provision does not
contravene requirements applicable to Standard Form 312, (Classified
Information Nondisclosure Agreement), Form 4414 (Sensitive Compartmented
Information Nondisclosure Agreement), or any other form issued by a
Federal department or agency governing the nondisclosure of classified
information.

(d) Representation. By submission of its offer, the Offeror represents
that it will not require its employees or subContractors to sign or
comply with internal confidentiality agreements or statements
prohibiting or otherwise restricting such employees or subContractors
from lawfully reporting waste, fraud, or abuse related to the
performance of a Government contract to a designated investigative or
law enforcement representative of a Federal department or agency
authorized to receive such information (e.g., agency Office of the
Inspector General).

(End of provision)

**FAR 52.232-22 Limitation of Funds (Apr 1984)**  
(a) The parties estimate that performance of this contract will not cost
the Government more than (1) the estimated cost specified in the
Schedule or, (2) if this is a cost-sharing contract, the Government’s
share of the estimated cost specified in the Schedule. The Contractor
agrees to use its best efforts to perform the work specified in the
Schedule and all obligations under this contract within the estimated
cost, which, if this is a cost-sharing contract, includes both the
Government’s and the Contractor’s share of the cost.  
  
(b) The Schedule specifies the amount presently available for payment by
the Government and allotted to this contract, the items covered, the
Government’s share of the cost if this is a cost-sharing contract, and
the period of performance it is estimated the allotted amount will
cover. The parties contemplate that the Government will allot additional
funds incrementally to the contract up to the full estimated cost to the
Government specified in the Schedule, exclusive of any fee. The
Contractor agrees to perform, or have performed, work on the contract up
to the point at which the total amount paid and payable by the
Government under the contract approximates but does not exceed the total
amount actually allotted by the Government to the contract.  
  
(c) The Contractor shall notify the Contracting Officer in writing
whenever it has reason to believe that the costs it expects to incur
under this contract in the next 60 days, when added to all costs
previously incurred, will exceed 75 percent of (1) the total amount so
far allotted to the contract by the Government or, (2) if this is a
cost-sharing contract, the amount then allotted to the contract by the
Government plus the Contractor’s corresponding share. The notice shall
state the estimated amount of additional funds required to continue
performance for the period specified in the Schedule.  
  
(d) Sixty days before the end of the period specified in the Schedule,
the Contractor shall notify the Contracting Officer in writing of the
estimated amount of additional funds, if any, required to continue
timely performance under the contract or for any further period
specified in the Schedule or otherwise agreed upon, and when the funds
will be required.  
  
(e) If, after notification, additional funds are not allotted by the end
of the period specified in the Schedule or another agreed-upon date,
upon the Contractor’s written request the Contracting Officer will
terminate this contract on that date in accordance with the provisions
of the Termination clause of this contract. If the Contractor estimates
that the funds available will allow it to continue to discharge its
obligations beyond that date, it may specify a later date in its
request, and the Contracting Officer may terminate this contract on that
later date.  
  
(f) Except as required by other provisions of this contract,
specifically citing and stated to be an exception to this clause—  
  
(1) The Government is not obligated to reimburse the Contractor for
costs incurred in excess of the total amount allotted by the Government
to this contract; and  
  
(2) The Contractor is not obligated to continue performance under this
contract (including actions under the Termination clause of this
contract) or otherwise incur costs in excess of—  
  
(i) The amount then allotted to the contract by the Government or;  
  
(ii) If this is a cost-sharing contract, the amount then allotted by the
Government to the contract plus the Contractor’s corresponding share,
until the Contracting Officer notifies the Contractor in writing that
the amount allotted by the Government has been increased and specifies
an increased amount, which shall then constitute the total amount
allotted by the Government to this contract.  
  
(g) The estimated cost shall be increased to the extent that (1) the
amount allotted by the Government or, (2) if this is a cost-sharing
contract, the amount then allotted by the Government to the contract
plus the Contractor’s corresponding share, exceeds the estimated cost
specified in the Schedule. If this is a cost-sharing contract, the
increase shall be allocated in accordance with the formula specified in
the Schedule.  
  
(h) No notice, communication, or representation in any form other than
that specified in paragraph (f)(2) of this clause, or from any person
other than the Contracting Officer, shall affect the amount allotted by
the Government to this contract. In the absence of the specified notice,
the Government is not obligated to reimburse the Contractor for any
costs in excess of the total amount allotted by the Government to this
contract, whether incurred during the course of the contract or as a
result of termination.  
  
(i) When and to the extent that the amount allotted by the Government to
the contract is increased, any costs the Contractor incurs before the
increase that are in excess of—  
  
(1) The amount previously allotted by the Government or;  
  
(2) If this is a cost-sharing contract, the amount previously allotted
by the Government to the contract plus the Contractor’s corresponding
share, shall be allowable to the same extent as if incurred afterward,
unless the Contracting Officer issues a termination or other notice and
directs that the increase is solely to cover termination or other
specified expenses.  
  
(j) Change orders shall not be considered an authorization to exceed the
amount allotted by the Government specified in the Schedule, unless they
contain a statement increasing the amount allotted.  
  
(k) Nothing in this clause shall affect the right of the Government to
terminate this contract. If this contract is terminated, the Government
and the Contractor shall negotiate an equitable distribution of all
property produced or purchased under the contract, based upon the share
of costs incurred by each.  
  
(l) If the Government does not allot sufficient funds to allow
completion of the work, the Contractor is entitled to a percentage of
the fee specified in the Schedule equalling the percentage of completion
of the work contemplated by this contract.
